#!/usr/bin/env python
"""Usage:
        chapman-kill <config> <name> [options]

Options:
  -h --help                 show this help message and exit
  -e --event EVENT          event to send [default: kill]
"""

import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

log = None


def main(args):
    from chapman import model as M
    log.info('Sending %s to %s', args['--event'], args['<name>'])
    M.Message.channel.pub(args['--event'], args['<name>'])

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    bootstrap(args['<config>'])
    log = logging.getLogger('chapman-kill')
    main(args)
