#!/usr/bin/env python
"""Usage:
        chapmand <config> [options]

Options:
  -h --help                 show this help message and exit
  -n,--name NAME            set the name of the worker
  -Q,--queues QUEUES        comma-separated list of queues [default: chapman]
  -c,--concurrency THREADS  number of threads to run [default: 1]
  -s,--sleep SLEEP          seconds to sleep when there is no work [default: 1]
  -d,--debug                drop into a debugger on task errors?
"""

import os
import time
import socket
import logging
import threading

from docopt import docopt
from pyramid.paster import bootstrap

log = None

def main(args):
    from chapman import worker
    name = args['--name']
    queues = args['--queues'].split(',')
    sleep = int(args['--sleep'])
    debug = bool(args['--debug'])
    if name is None:
        name = 'chapmand-%s-%s' % (
            socket.getfqdn(), os.getpid())
    log.info('Starting chapmand %s: listening on %s', name, queues)
    num_threads = int(args['--concurrency'])
    w = worker.Worker(
        name, queues, num_threads=num_threads, raise_errors=args['--debug'])
    w.start()
    while True:
        time.sleep(30)
        log.info('--- mark ---')

if __name__ == '__main__':
    args = docopt(__doc__)
    logging.config.fileConfig(
        args['<config>'],
        defaults=dict(here=os.getcwd()))
    bootstrap(args['<config>'])
    log = logging.getLogger('chapmand')
    main(args)
