#!/usr/bin/env python
"""Usage:
        chapman-init <config> [options]

Options:
  -h --help              show this help message and exit
"""
import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

from chapman import model as M

log = None


def main(args):
    log.info('Starting chapman-init')
    db = M.doc_session.db
    if 'chapman.event' in db.collection_names():
        db['chapman.event'].drop()
    M.Message.channel.ensure_channel()

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    bootstrap(args['<config>'], options=dict(noweb='true'))
    log = logging.getLogger('chapman-init')
    main(args)
