#!/usr/bin/env python
"""Usage:
        chapman-kill <config> <name>

Options:
  -h --help                 show this help message and exit
"""

import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

log = None


def main(args):
    from chapman import model as M
    M.Message.channel.pub('kill', args['<name>'])

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    bootstrap(args['<config>'])
    log = logging.getLogger('chapman-kill')
    main(args)
