#!/usr/bin/env python
"""Usage:
        chapmanev <config> [options]

Options:
  -h --help              show this help message and exit
"""

import time
import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

from chapman import model as M

log = None


def main(args):
    args = docopt(__doc__)
    log.info('Starting chapmanev')
    mainloop(args)


def mainloop(args):
    chan = M.Message.channel.new_channel()

    @chan.sub('')
    def handler(chan, ev):
        msg = M.Message.m.get(_id=ev['data'])
        if msg is not None:
            log.info('%r', msg)
        else:
            log.info('%r', ev)
    while True:
        chan.handle_ready(raise_errors=True, await=True)
        time.sleep(0.1)

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    bootstrap(args['<config>'])
    log = logging.getLogger('chapmanev')
    main(args)
