#!/usr/bin/env python
"""Usage:
        chapmans <config> [options]

Options:
  -h --help                 show this help message and exit
  -n,--name NAME            set the name of the worker
"""

import os
import socket
import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

log = None


def main(args, app_context):
    from chapman import sworker
    name = args['--name']
    if name is None:
        name = 'chapmans-%s-%s' % (
            socket.getfqdn(), os.getpid())
    log.info('Starting chapmans %s', name)
    w = sworker.ShardWorker(
        '%s:%s' % (name, os.getpid()),
        app_context=app_context)
    w.start()
    w.run()

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    app_context = bootstrap(args['<config>'])
    log = logging.getLogger('chapmand')
    main(args, app_context)
