#!/usr/bin/env python
"""Usage:
        chapmand <config> [options]

Options:
  -h --help                 show this help message and exit
  -n,--name NAME            set the name of the worker
  -Q,--queues QUEUES        comma-separated list of queues [default: chapman]
  -c,--concurrency THREADS  number of threads to run [default: 1]
  -d,--debug                drop into a debugger on task errors?
"""

import os
import socket
import logging

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

log = None


def main(args, app_context):
    from chapman import worker
    name = args['--name']
    queues = args['--queues'].split(',')
    debug = bool(args['--debug'])
    if name is None:
        name = 'chapmand-%s-%s' % (
            socket.getfqdn(), os.getpid())
    log.info('Starting chapmand %s: listening on %s', name, queues)
    num_threads = int(args['--concurrency'])
    w = worker.Worker(
        '%s:%s' % (name, os.getpid()),
        queues,
        num_threads=num_threads,
        raise_errors=debug,
        app_context=app_context)
    w.start()
    w.run()

if __name__ == '__main__':
    args = docopt(__doc__)
    setup_logging(args['<config>'])
    app_context = bootstrap(args['<config>'])
    log = logging.getLogger('chapmand')
    main(args, app_context)
