#!/usr/bin/env python
"""Usage:
        chapman-kill <config> <name>

Options:
  -h --help                 show this help message and exit
"""

import os
import time
import socket
import logging
import threading

from docopt import docopt
from pyramid.paster import bootstrap

log = None

def main(args):
    from chapman import model as M
    chan = M.Event.channel()
    chan.pub('kill', args['<name>'])

if __name__ == '__main__':
    args = docopt(__doc__)
    logging.config.fileConfig(
        args['<config>'],
        defaults=dict(here=os.getcwd()))
    bootstrap(args['<config>'])
    log = logging.getLogger('chapmand')
    main(args)
