#!/usr/bin/env python
"""Usage:
        chapman-ping <config> [options]

Options:
  -h --help                 show this help message and exit
"""
import os
import time
import socket
import logging
import threading

from docopt import docopt
from pyramid.paster import bootstrap, setup_logging

log = None

def main(args):
    from chapman import model as M
    responses = []
    chan = M.Event.channel()
    t = threading.Thread(target=target, args=(chan,))
    t.setDaemon(True)
    t.start()
    log.info('Starting ping...')
    while True:
        chan.pub('ping')
        time.sleep(1)

def target(chan):
    @chan.sub('pong')
    def handler(chan, msg):
        log.info('pong: %s', msg['data'])
    while True:
        chan.handle_ready(raise_errors=True, await=True)
        time.sleep(0.1)

if __name__ == '__main__':
    args = docopt(__doc__)
    # logging.config.fileConfig(
    #     args['<config>'],
    #     defaults=dict(here=os.getcwd()))
    setup_logging(args['<config>'])
    bootstrap(args['<config>'], options=dict(noweb='true'))
    log = logging.getLogger('chapmand')
    main(args)
